package l4lbdrv

// This file is auto generated by gen_bindings.go. Do not modify.

import (
	"bytes"
	"fmt"
	"strings"
	"unsafe"
)

// Source: ../c/lb.c

const (
	SELECTION_ALGORITHM_MODULO     = 0     // ../c/lb.c:95
	SELECTION_ALGORITHM_RENDEZVOUS = 1     // ../c/lb.c:96
	SELECTION_ALGORITHM_MAGLEV     = 2     // ../c/lb.c:97
	MAGLEV_LOOKUP_SIZE             = 65537 // ../c/lb.c:100
	DESTINATIONS_SIZE              = 255   // ../c/lb.c:140
)

type StatCounters struct { // ../c/lb.c:51
	RxPacketTotal                 uint64 // ../c/lb.c:52
	RxTotalSize                   uint64 // ../c/lb.c:53
	TooShortPacketTotal           uint64 // ../c/lb.c:55
	UnsupportedNetworkPacketTotal uint64 // ../c/lb.c:56
	Ipv4PacketTotal               uint64 // ../c/lb.c:57
	Ipv6PacketTotal               uint64 // ../c/lb.c:58
	UdpPacketTotal                uint64 // ../c/lb.c:59
	IpOptionPacketTotal           uint64 // ../c/lb.c:60
	NonSupportedProtoPacketTotal  uint64 // ../c/lb.c:61
	NoVipMatchTotal               uint64 // ../c/lb.c:62
	NoHealthyDestinationTotal     uint64 // ../c/lb.c:63
	MtuExceededPacketTotal        uint64 // ../c/lb.c:64
	Icmpv4FragNeededTotal         uint64 // ../c/lb.c:65
	Icmpv6PacketTooBigTotal       uint64 // ../c/lb.c:66
	InvalidIcmpErrorTotal         uint64 // ../c/lb.c:67
	Icmpv4ErrorForwardedTotal     uint64 // ../c/lb.c:68
	Icmpv6ErrorForwardedTotal     uint64 // ../c/lb.c:69
	FailedAdjustHeadTotal         uint64 // ../c/lb.c:70
	FailedAdjustTailTotal         uint64 // ../c/lb.c:71
}

func StatCountersAssertLayout(s *DWARFStruct) error {
	if s == nil {
		return fmt.Errorf("DWARFStruct is nil")
	}

	gosize := unsafe.Sizeof(StatCounters{})
	if gosize != uintptr(s.Size) {
		return fmt.Errorf("size mismatch: go: %d, dwarf: %d", gosize, s.Size)
	}

	fs := s.Fields

	var goff uintptr
	var doff int64
	goff = unsafe.Offsetof(StatCounters{}.RxPacketTotal)
	doff = fs["rx_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go RxPacketTotal: %d, dwarf rx_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.RxTotalSize)
	doff = fs["rx_total_size"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go RxTotalSize: %d, dwarf rx_total_size: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.TooShortPacketTotal)
	doff = fs["too_short_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go TooShortPacketTotal: %d, dwarf too_short_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.UnsupportedNetworkPacketTotal)
	doff = fs["unsupported_network_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go UnsupportedNetworkPacketTotal: %d, dwarf unsupported_network_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.Ipv4PacketTotal)
	doff = fs["ipv4_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Ipv4PacketTotal: %d, dwarf ipv4_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.Ipv6PacketTotal)
	doff = fs["ipv6_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Ipv6PacketTotal: %d, dwarf ipv6_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.UdpPacketTotal)
	doff = fs["udp_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go UdpPacketTotal: %d, dwarf udp_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.IpOptionPacketTotal)
	doff = fs["ip_option_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go IpOptionPacketTotal: %d, dwarf ip_option_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.NonSupportedProtoPacketTotal)
	doff = fs["non_supported_proto_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go NonSupportedProtoPacketTotal: %d, dwarf non_supported_proto_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.NoVipMatchTotal)
	doff = fs["no_vip_match_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go NoVipMatchTotal: %d, dwarf no_vip_match_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.NoHealthyDestinationTotal)
	doff = fs["no_healthy_destination_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go NoHealthyDestinationTotal: %d, dwarf no_healthy_destination_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.MtuExceededPacketTotal)
	doff = fs["mtu_exceeded_packet_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go MtuExceededPacketTotal: %d, dwarf mtu_exceeded_packet_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.Icmpv4FragNeededTotal)
	doff = fs["icmpv4_frag_needed_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Icmpv4FragNeededTotal: %d, dwarf icmpv4_frag_needed_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.Icmpv6PacketTooBigTotal)
	doff = fs["icmpv6_packet_too_big_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Icmpv6PacketTooBigTotal: %d, dwarf icmpv6_packet_too_big_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.InvalidIcmpErrorTotal)
	doff = fs["invalid_icmp_error_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go InvalidIcmpErrorTotal: %d, dwarf invalid_icmp_error_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.Icmpv4ErrorForwardedTotal)
	doff = fs["icmpv4_error_forwarded_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Icmpv4ErrorForwardedTotal: %d, dwarf icmpv4_error_forwarded_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.Icmpv6ErrorForwardedTotal)
	doff = fs["icmpv6_error_forwarded_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Icmpv6ErrorForwardedTotal: %d, dwarf icmpv6_error_forwarded_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.FailedAdjustHeadTotal)
	doff = fs["failed_adjust_head_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go FailedAdjustHeadTotal: %d, dwarf failed_adjust_head_total: %d", goff, doff)
	}
	goff = unsafe.Offsetof(StatCounters{}.FailedAdjustTailTotal)
	doff = fs["failed_adjust_tail_total"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go FailedAdjustTailTotal: %d, dwarf failed_adjust_tail_total: %d", goff, doff)
	}

	return nil
}

func (c *StatCounters) Add(other *StatCounters) {
	c.RxPacketTotal += other.RxPacketTotal
	c.RxTotalSize += other.RxTotalSize
	c.TooShortPacketTotal += other.TooShortPacketTotal
	c.UnsupportedNetworkPacketTotal += other.UnsupportedNetworkPacketTotal
	c.Ipv4PacketTotal += other.Ipv4PacketTotal
	c.Ipv6PacketTotal += other.Ipv6PacketTotal
	c.UdpPacketTotal += other.UdpPacketTotal
	c.IpOptionPacketTotal += other.IpOptionPacketTotal
	c.NonSupportedProtoPacketTotal += other.NonSupportedProtoPacketTotal
	c.NoVipMatchTotal += other.NoVipMatchTotal
	c.NoHealthyDestinationTotal += other.NoHealthyDestinationTotal
	c.MtuExceededPacketTotal += other.MtuExceededPacketTotal
	c.Icmpv4FragNeededTotal += other.Icmpv4FragNeededTotal
	c.Icmpv6PacketTooBigTotal += other.Icmpv6PacketTooBigTotal
	c.InvalidIcmpErrorTotal += other.InvalidIcmpErrorTotal
	c.Icmpv4ErrorForwardedTotal += other.Icmpv4ErrorForwardedTotal
	c.Icmpv6ErrorForwardedTotal += other.Icmpv6ErrorForwardedTotal
	c.FailedAdjustHeadTotal += other.FailedAdjustHeadTotal
	c.FailedAdjustTailTotal += other.FailedAdjustTailTotal
}

func (c *StatCounters) String() string {
	var buf bytes.Buffer
	buf.WriteString("StatCounters{")
	if c.RxPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("RxPacketTotal=%d, ", c.RxPacketTotal))
	}
	if c.RxTotalSize != 0 {
		buf.WriteString(fmt.Sprintf("RxTotalSize=%d, ", c.RxTotalSize))
	}
	if c.TooShortPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("TooShortPacketTotal=%d, ", c.TooShortPacketTotal))
	}
	if c.UnsupportedNetworkPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("UnsupportedNetworkPacketTotal=%d, ", c.UnsupportedNetworkPacketTotal))
	}
	if c.Ipv4PacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("Ipv4PacketTotal=%d, ", c.Ipv4PacketTotal))
	}
	if c.Ipv6PacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("Ipv6PacketTotal=%d, ", c.Ipv6PacketTotal))
	}
	if c.UdpPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("UdpPacketTotal=%d, ", c.UdpPacketTotal))
	}
	if c.IpOptionPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("IpOptionPacketTotal=%d, ", c.IpOptionPacketTotal))
	}
	if c.NonSupportedProtoPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("NonSupportedProtoPacketTotal=%d, ", c.NonSupportedProtoPacketTotal))
	}
	if c.NoVipMatchTotal != 0 {
		buf.WriteString(fmt.Sprintf("NoVipMatchTotal=%d, ", c.NoVipMatchTotal))
	}
	if c.NoHealthyDestinationTotal != 0 {
		buf.WriteString(fmt.Sprintf("NoHealthyDestinationTotal=%d, ", c.NoHealthyDestinationTotal))
	}
	if c.MtuExceededPacketTotal != 0 {
		buf.WriteString(fmt.Sprintf("MtuExceededPacketTotal=%d, ", c.MtuExceededPacketTotal))
	}
	if c.Icmpv4FragNeededTotal != 0 {
		buf.WriteString(fmt.Sprintf("Icmpv4FragNeededTotal=%d, ", c.Icmpv4FragNeededTotal))
	}
	if c.Icmpv6PacketTooBigTotal != 0 {
		buf.WriteString(fmt.Sprintf("Icmpv6PacketTooBigTotal=%d, ", c.Icmpv6PacketTooBigTotal))
	}
	if c.InvalidIcmpErrorTotal != 0 {
		buf.WriteString(fmt.Sprintf("InvalidIcmpErrorTotal=%d, ", c.InvalidIcmpErrorTotal))
	}
	if c.Icmpv4ErrorForwardedTotal != 0 {
		buf.WriteString(fmt.Sprintf("Icmpv4ErrorForwardedTotal=%d, ", c.Icmpv4ErrorForwardedTotal))
	}
	if c.Icmpv6ErrorForwardedTotal != 0 {
		buf.WriteString(fmt.Sprintf("Icmpv6ErrorForwardedTotal=%d, ", c.Icmpv6ErrorForwardedTotal))
	}
	if c.FailedAdjustHeadTotal != 0 {
		buf.WriteString(fmt.Sprintf("FailedAdjustHeadTotal=%d, ", c.FailedAdjustHeadTotal))
	}
	if c.FailedAdjustTailTotal != 0 {
		buf.WriteString(fmt.Sprintf("FailedAdjustTailTotal=%d, ", c.FailedAdjustTailTotal))
	}
	if strings.HasSuffix(buf.String(), ", ") {
		buf.Truncate(buf.Len() - 2)
	}
	buf.WriteString("}")
	return buf.String()
}

type LbConfig struct { // ../c/lb.c:84
	Vip4Address        uint32    // ../c/lb.c:85
	Vip6Address        [16]uint8 // ../c/lb.c:86
	SrcIp6Address      [16]uint8 // ../c/lb.c:87
	SrcMacAddress      [6]uint8  // ../c/lb.c:88
	UdpDestPort        uint16    // ../c/lb.c:89
	NumDests           uint32    // ../c/lb.c:90
	InnerMtu           uint32    // ../c/lb.c:91
	SelectionAlgorithm uint32    // ../c/lb.c:92
}

func LbConfigAssertLayout(s *DWARFStruct) error {
	if s == nil {
		return fmt.Errorf("DWARFStruct is nil")
	}

	gosize := unsafe.Sizeof(LbConfig{})
	if gosize != uintptr(s.Size) {
		return fmt.Errorf("size mismatch: go: %d, dwarf: %d", gosize, s.Size)
	}

	fs := s.Fields

	var goff uintptr
	var doff int64
	goff = unsafe.Offsetof(LbConfig{}.Vip4Address)
	doff = fs["vip4_address"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Vip4Address: %d, dwarf vip4_address: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.Vip6Address)
	doff = fs["vip6_address"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go Vip6Address: %d, dwarf vip6_address: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.SrcIp6Address)
	doff = fs["src_ip6_address"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go SrcIp6Address: %d, dwarf src_ip6_address: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.SrcMacAddress)
	doff = fs["src_mac_address"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go SrcMacAddress: %d, dwarf src_mac_address: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.UdpDestPort)
	doff = fs["udp_dest_port"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go UdpDestPort: %d, dwarf udp_dest_port: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.NumDests)
	doff = fs["num_dests"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go NumDests: %d, dwarf num_dests: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.InnerMtu)
	doff = fs["inner_mtu"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go InnerMtu: %d, dwarf inner_mtu: %d", goff, doff)
	}
	goff = unsafe.Offsetof(LbConfig{}.SelectionAlgorithm)
	doff = fs["selection_algorithm"].Offset
	if goff != uintptr(doff) {
		return fmt.Errorf("offset mismatch: go SelectionAlgorithm: %d, dwarf selection_algorithm: %d", goff, doff)
	}

	return nil
}

func LbAssertLayout(m map[string]*DWARFStruct) error {
	if err := StatCountersAssertLayout(m["stat_counters"]); err != nil {
		return fmt.Errorf("stat_counters: %v", err)
	}
	if err := LbConfigAssertLayout(m["lb_config"]); err != nil {
		return fmt.Errorf("lb_config: %v", err)
	}
	return nil
}
