server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location = /relay-fingerprint {
        proxy_pass https://relay:4443/fingerprint;
        proxy_ssl_verify off;
    }

    location = /metrics {
        proxy_pass http://relay:9090/metrics;
    }
}
