[log]
level = "info"

[server]
bind = "[::]:4443"
tls.generate = ["localhost", "relay"]

[web.http]
listen = "[::]:4443"

[auth]
public = ""

[cache]
capacity = "128MB"
duration = "30s"

[stats]
enabled = true
node = "edge-c0"
